### ISSUE TITLE
EBattlEyeCommand and IBattleNET missing from nuget 1.3.4

### ISSUE THREAD

**Issue by Bluscream** [marceldev89/BattleNET#51]
![image](https://github.com/marceldev89/BattleNET/assets/3318223/216f3f2c-914a-4f40-8fda-170cb0a88757)

**Comment by marceldev89** [comment]
Seems like you're NuGet-ting the wrong package because those words don't exist in my code 😛

**Comment by Bluscream** [comment]
> Seems like you're NuGet-ting the wrong package because those words don't exist in my code 😛

[BattleNET.zip](https://github.com/marceldev89/BattleNET/files/14542641/BattleNET.zip) is not your package? if so who'se is. (has the same nuget name)

The link in your readme even links to the same user https://forums.dayz.com/topic/23967-battlenet-c-library-and-client-for-the-battleye-protocol/ which does reference [IBattleNet](https://forums.dayz.com/topic/23967-battlenet-c-library-and-client-for-the-battleye-protocol/?tab=comments#comment-376071)

**Comment by marceldev89** [comment]
Can you send me the link to the nuget package?
```
[marcel@arch BattleNET (master =)]$ rg "IBattleNET"
[marcel@arch BattleNET (master =)]$
```
Nothing found 😅

**Comment by marceldev89** [comment]
oh WAIT, that's really old code on that forum.. Those things just don't exist anymore.

https://github.com/marceldev89/BattleNET/commit/ae9e592d135c2201201534f5f3a678372a7b52ce

**Comment by marceldev89** [comment]
Check https://github.com/marceldev89/BattleNET/blob/master/BattleNET%20client/Program.cs for an up-to-date example client

**Comment by Bluscream** [comment]
Damn. I really hoped i could get this working. Thanks anyway 😞
